import uuid
import random
import string
from django.db import models
from django.utils import timezone


def generate_pass_id():
    """Generate a short, human-readable pass ID like GST-A3F9XY."""
    chars = string.ascii_uppercase + string.digits
    suffix = "".join(random.choices(chars, k=6))
    return f"GST-{suffix}"


class GuestPass(models.Model):
    class Status(models.TextChoices):
        ACTIVE = "ACTIVE", "Active (Inside)"
        CHECKED_OUT = "CHECKED_OUT", "Checked Out (Approved)"
        STOLEN_FLAG = "STOLEN_FLAG", "Stolen / Flagged"
        DENIED = "DENIED", "Denied"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    pass_id = models.CharField(
        max_length=12,
        unique=True,
        default=generate_pass_id,
        editable=False,
        db_index=True,
        help_text="Short unique ID generated by system (e.g. GST-A3F9XY) given to guest.",
    )

    guest_name = models.CharField(
        max_length=150,
        blank=True,
        help_text="Optional name of the guest.",
    )
    guest_id_doc = models.CharField(
        max_length=100,
        blank=True,
        help_text="Physical ID/Passport number if entered as text.",
    )
    id_photo = models.ImageField(
        upload_to="guest_id_photos/",
        blank=True,
        null=True,
        help_text="Picture of the physical ID / Passport taken by guard at check-in.",
    )
    serial_number = models.CharField(
        max_length=150,
        blank=True,
        help_text="Serial number of the guest's device/laptop.",
    )

    guard = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="guest_passes",
        help_text="Guard who registered the guest.",
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
    )

    flagged_as_stolen = models.BooleanField(
        default=False,
        help_text="Flagged as stolen or unauthorized during checkout verification.",
    )

    checked_in_at = models.DateTimeField(auto_now_add=True)
    checked_out_at = models.DateTimeField(null=True, blank=True)

    checkout_notes = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ["-checked_in_at"]
        verbose_name = "Guest Pass"
        verbose_name_plural = "Guest Passes"

    def __str__(self):
        return f"{self.pass_id} — SN:{self.serial_number or 'N/A'} [{self.status}]"

    def submit_decision(self, decision: str, notes: str = ""):
        """
        Record the guard's checkout decision:
        - APPROVED: Guest and device verified, leaves campus safely.
        - STOLEN_FLAG: Device flagged as stolen / mismatch, alerts department.
        - DENIED: Checkout denied.
        """
        decision_upper = decision.strip().upper()
        if decision_upper == "APPROVED":
            self.status = self.Status.CHECKED_OUT
            self.flagged_as_stolen = False
        elif decision_upper in ("STOLEN_FLAG", "STOLEN"):
            self.status = self.Status.STOLEN_FLAG
            self.flagged_as_stolen = True
        elif decision_upper == "DENIED":
            self.status = self.Status.DENIED
            self.flagged_as_stolen = False
        else:
            self.status = self.Status.CHECKED_OUT

        self.checkout_notes = notes
        self.checked_out_at = timezone.now()
        self.save()
