# Generated by Django 5.2.16 on 2026-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_setup_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_setup_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces user to set a new password before accessing the system'),
        ),
    ]
