# Generated by Django 5.2.16 on 2026-08-17 18:29

import django.db.models.deletion
import guests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_id', models.CharField(db_index=True, default=guests.models.generate_pass_id, editable=False, help_text='Short human-readable ID given to the guest (e.g. GST-A3F9).', max_length=12, unique=True)),
                ('guest_name', models.CharField(blank=True, help_text='Optional name of the guest.', max_length=150)),
                ('guest_id_doc', models.CharField(help_text='Physical ID number provided by the guest (national ID, passport, etc.).', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number of the device the guest is carrying in.', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (Checked In)'), ('CHECKED_OUT', 'Checked Out')], default='ACTIVE', max_length=20)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_matched', models.BooleanField(blank=True, help_text='True if check-out serial/ID matched check-in record; False if mismatch.', null=True)),
                ('checkout_notes', models.CharField(blank=True, max_length=500)),
                ('guard', models.ForeignKey(help_text='Guard who registered the guest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Pass',
                'verbose_name_plural': 'Guest Passes',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
