# Generated by Django 5.2.16 on 2026-08-18 07:32

import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestpass',
            name='checkout_matched',
        ),
        migrations.AddField(
            model_name='guestpass',
            name='flagged_as_stolen',
            field=models.BooleanField(default=False, help_text='Flagged as stolen or unauthorized during checkout verification.'),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='id_photo',
            field=models.ImageField(blank=True, help_text='Picture of the physical ID / Passport taken by guard at check-in.', null=True, upload_to='guest_id_photos/'),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='guest_id_doc',
            field=models.CharField(blank=True, help_text='Physical ID/Passport number if entered as text.', max_length=100),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='pass_id',
            field=models.CharField(db_index=True, default=guests.models.generate_pass_id, editable=False, help_text='Short unique ID generated by system (e.g. GST-A3F9XY) given to guest.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='serial_number',
            field=models.CharField(blank=True, help_text="Serial number of the guest's device/laptop.", max_length=150),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (Inside)'), ('CHECKED_OUT', 'Checked Out (Approved)'), ('STOLEN_FLAG', 'Stolen / Flagged'), ('DENIED', 'Denied')], default='ACTIVE', max_length=20),
        ),
    ]
