# Generated by Django 6.0.7 on 2026-08-04 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('STOLEN_FLAG', 'Stolen device flagged')], max_length=20)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='scan_evidence/')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='devices.pc')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
