# Generated by Django 5.2.16 on 2026-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='scan_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check-In'), ('CHECK_OUT', 'Check-Out')], default='CHECK_IN', help_text='CHECK_IN when device enters the building, CHECK_OUT when it leaves.', max_length=10),
        ),
    ]
